### PR TITLE
Add "sample_with_time" operator

### LINKED ISSUE #265: Add "sample_with_time" operator
"nebu" from discord requested implementation of `sample` and `sample_with_time` operators

### PR DESCRIPTION
**Pull request by victimsnino**
Partly resolves #265

### CODE REVIEW

**Comment by thorstink** [comment]
Awesome, thanks :-)

**Comment by victimsnino** [comment]
@thorstink, waiting for the feedback ;-)
BTW, do you still need sample with observable logic?

**Comment by thorstink** [comment]
Ah, I think I am missing something. What feedback? :-)

sample_with_time is something I would still like a lot. What I mean is
something similar to RxCpp's sample_with_time:
https://github.com/ReactiveX/RxCpp/blob/main/Rx/v2/test/operators/sample.cpp

Something that rxcpp does not have, but what I think would be nice (I've
noticed I wanted it sometimes), is a simple downsample operator. Pass one
message, skip three, pass one, skip three etc.

Or did you mean something else?

**Comment by victimsnino** [comment]
@thorstink ,

> Ah, I think I am missing something. What feedback? :-)

Feedback about usage =) As far as I remember you requested this operator =)

> sample_with_time is something I would still like a lot. What I mean is
something similar to RxCpp's sample_with_time:
https://github.com/ReactiveX/RxCpp/blob/main/Rx/v2/test/operators/sample.cpp

Yeah, rpp has same after this PR =)

> Something that rxcpp does not have, but what I think would be nice (I've
noticed I wanted it sometimes), is a simple downsample operator. Pass one
message, skip three, pass one, skip three etc.

Does it something like "take N elements each NNth element"?

**Pull request merged**
