### PR TITLE
Allocate one "never" observable per deduced type.

### PR DESCRIPTION
**Pull request by tcw165**

### CODE REVIEW

**Comment by victimsnino** [comment]
Are you sure that it will give some boost? For me it is really trivial action to construct observable with empty on_subscribe

**Comment by tcw165** [comment]
I reference to [RxJava implementation for never](https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/core/Observable.java#L3900) (or [declaration link](https://github.com/ReactiveX/RxJava/blob/5bb119b1489afe4fbc5bb51b828be95971ee8f1d/src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableNever.java)), where they declare that as an static instance.

But they use `Object` as type parameter in Java. 

> Are you sure that it will give some boost?

I think it would save the allocation for never-observable but hard to notice how much we could save honestly. Both never and empty are useful in difference cases.

For example on `never()`:

```
someUpstream
  .switch_,map([](const auto& val) {
    if (val == some_criteria) {
      return rpp::sources::never().as_dynamic();
    }

    return nextActionObservable();
  })
```

Here, using `never()` inside a `switch_map()` is an alternative way to using `.filter(...)`. However, using `never()` could reduce length of chain.

**Comment by victimsnino** [comment]
I see your point, but it doesn’t work in such a way :-) Anyway allocation would happens because static object inside function must be copied to return it from function. So, instead of construction you would do copy :-). One way to to avoid it: return const& on static object. In this case yes, object would be created only once and no any copies… but even in this case I’m not sure if it is faster…

**Comment by tcw165** [comment]
> Anyway allocation would happens because static object inside function must be copied to return it from function.

I see. Yup, the copy is happening.

> anyway, to see performance boost it is better to create benchmark ;-)

I'd like to learn to create a bench mark. Can you point me out some examples?

**Comment by victimsnino** [comment]
All RPP benchmarks have paced there 

https://github.com/victimsnino/ReactivePlusPlus/blob/main/src/tests/benchmarks.cpp

**Comment by victimsnino** [comment]
Any updates related to this one?

**Comment by victimsnino** [comment]
Delayed till we really need it

**Pull request closed without merging**
