### PR TITLE
Asio

### PR DESCRIPTION
**Pull request by victimsnino**

### CODE REVIEW

**Comment by iSplasher** [comment]
Hello, I'm currently interested in this Asio integration, are there any ways for me to help?

**Comment by victimsnino** [comment]
Hi @iSplasher !
Thank you a lot for the offer of help!
To be honest i can't find enough time to implement all recent requested things (grpc/asio and some operators) so it just delayed till completion other things. If you want, you can implement logic by your own and send PR. I'm not very familiar with asio so it could help me a lot if you are good at it! I would provide sufficient feedback/comments during PR to implement it better in terms of RPP. It can be incremental process (you can write small pieces inside your own PR, get some comments/feedback and write some extra things and etc till it would be completed =))

How can i help you to help me? =)

**Comment by iSplasher** [comment]
Great, that's much of what I wanted to know. I'll clone this PR and try to implement it. I'm in the middle of exams so progress will be slow, that means you don't need to wait for me :)

**Comment by victimsnino** [comment]
> Great, that's much of what I wanted to know. I'll clone this PR and try to implement it. I'm in the middle of exams so progress will be slow, that means you don't need to wait for me :)

Yeah, sure, you are welcome to ask anything =) (BTW: rpp has discord server, you can join and ask anything [there](https://discord.com/invite/KWMR3RNkVz)). Good luck with exams and I'm pretty sure you would implement it a lot faster than me =D

**Comment by victimsnino** [comment]
Closing due to #627

**Pull request closed without merging**
