### PR TITLE
Fix observer disposing after on_erorr/on_completed

### PR DESCRIPTION
**Pull request by victimsnino**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new `boolean_disposables_strategy` class for improved disposal state management.
	- Added a new `Boolean` mode to enhance observer control over disposal states.

- **Improvements**
	- Updated various observer strategies to use the new `Boolean` disposables mode, streamlining error handling and state management.
	- Removed redundant local disposal checks from several observer strategies, enhancing clarity and efficiency.

- **Bug Fixes**
	- Enhanced test cases to ensure proper validation of disposal states during observable operations.

### CODE REVIEW

**Comment by daixtrose** [comment]
I am sorry to have no solution but as an observer (sic!), I wonder why any RX C++ implementation ends in a mess of checking bools and (sub-)states like hell. Is this embedded in the problem domain? Is there no way to escape this? I mean, it is a paradox: a functional-style monad implementation is built out of state machines.

**Comment by daixtrose** [comment]
You may remember me ranting about `dispose()` a while ago. Here, we have code that reads `return locally_disposed || disposable->is_disposed();`. I may resolve this in a decade, but this code looks wrong to me. I cannot express why.

**Comment by victimsnino** [comment]
> I am sorry to have no solution but as an observer (sic!), I wonder why any RX C++ implementation ends in a mess of checking bools and (sub-)states like hell. Is this embedded in the problem domain? Is there no way to escape this? I mean, it is a paradox: a functional-style monad implementation is built out of state machines.

it is interesting point =D Yeah, anyway you have to check for some states, it is pretty natural - you are hiding state from user, but state should be handled somehow. Regarding this one: it appears just from optimization due to removing exact disposable state inside observer and changing it to lihtweight bool + external state. Anyway, yeah, i'm going to rewrite it a bit, just was doublechecking CI is ok

**Comment by daixtrose** [comment]
> it is interesting point =D Yeah, anyway you have to check for some states, it is pretty natural - you are hiding state from user, but state should be handled somehow. Regarding this one: it appears just from optimization due to removing exact disposable state inside observer and changing it to lihtweight bool + external state. Anyway, yeah, i'm going to rewrite it a bit, just was doublechecking CI is ok

My problem is that the code does not hide the *payload* state that travels down the queue from the user; it is the extra janitor stuff that needs stateful expressions. This will get messy when we enter multi-threaded environments.

**Comment by daixtrose** [comment]
> > I am sorry to have no solution but as an observer (sic!), I wonder why any RX C++ implementation ends in a mess of checking bools and (sub-)states like hell. Is this embedded in the problem domain? Is there no way to escape this? I mean, it is a paradox: a functional-style monad implementation is built out of state machines.
> 
> it is interesting point =D Yeah, anyway you have to check for some states, it is pretty natural - you are hiding state from user, but state should be handled somehow. Regarding this one: it appears just from optimization due to removing exact disposable state inside observer and changing it to lihtweight bool + external state. Anyway, yeah, i'm going to rewrite it a bit, just was doublechecking CI is ok

What happens if you try not to use bools but the lifetime of objects?

**Comment by victimsnino** [comment]
> You may remember me ranting about `dispose()` a while ago. Here, we have code that reads `return locally_disposed || disposable->is_disposed();`. I may resolve this in a decade, but this code looks wrong to me. I cannot express why.

updated a bit to be a bit more clear, was just first version to be sure fix is valid

**Comment by victimsnino** [comment]
> > it is interesting point =D Yeah, anyway you have to check for some states, it is pretty natural - you are hiding state from user, but state should be handled somehow. Regarding this one: it appears just from optimization due to removing exact disposable state inside observer and changing it to lihtweight bool + external state. Anyway, yeah, i'm going to rewrite it a bit, just was doublechecking CI is ok
> 
> My problem is that the code does not hide the _payload_ state that travels down the queue from the user; it is the extra janitor stuff that needs stateful expressions. This will get messy when we enter multi-threaded environments.

Not sure if i get your point

**Comment by victimsnino** [comment]
> > > I am sorry to have no solution but as an observer (sic!), I wonder why any RX C++ implementation ends in a mess of checking bools and (sub-)states like hell. Is this embedded in the problem domain? Is there no way to escape this? I mean, it is a paradox: a functional-style monad implementation is built out of state machines.
> > 
> > 
> > it is interesting point =D Yeah, anyway you have to check for some states, it is pretty natural - you are hiding state from user, but state should be handled somehow. Regarding this one: it appears just from optimization due to removing exact disposable state inside observer and changing it to lihtweight bool + external state. Anyway, yeah, i'm going to rewrite it a bit, just was doublechecking CI is ok
> 
> What happens if you try not to use bools but the lifetime of objects?

It is correct question and it is why bools exists. Correct answer is "same". These bools are just optimization to NOT have unnecessary lifetime objects. But it is hidden from users

**Pull request merged**
